spring.application.name=e-menu

# SQL Server Configuration - SQL Authentication
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=emenu_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
server.servlet.multipart.max-file-size=50MB
server.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-post-size=52428800
